[contest]
name = "toi-2021 test"
description = "toi-2021 test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++14 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++14 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "A"
title = "A. 原始人排序"
time_limit = 1
[tasks.inclusive_tests]
2 = ["1"]

[[tasks]]
name = "B"
title = "B. 掃地機器人"
time_limit = 1
[tasks.inclusive_tests]
2 = ["1"]

[[tasks]]
name = "C"
title = "C. 粉刷護欄"
time_limit = 1
[tasks.inclusive_tests]
2 = ["1"]
3 = ["2", "1"]

[[tasks]]
name = "D"
title = "D. 乘車時間"
time_limit = 5
[tasks.inclusive_tests]
4 = ["3", "2", "1"]

[[tasks]]
name = "E"
title = "E. 密室逃脫"
time_limit = 5
[tasks.inclusive_tests]
2 = ["1"]
3 = ["2", "1"]
4 = ["3", "2", "1"]
